### ISSUE TITLE
System root certificates, wildcard certificates, hostname_mismatch

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ssl#21]
What is the best way to establish an SSL connection using only the **system** root certificates?

From the documentation, I get the impression that one way to do it is:

<pre>
:- use_module(library(ssl)).

ssl(Host, Port, SecureRead, SecureWrite) :-
        ssl_context(client, SSL, [<b>cacert_file(system(root_certificates)),
                                  cert_verify_hook(my_verify)</b>]),
        tcp_connect(Host:Port, StreamPair, []),
        stream_pair(StreamPair, Read, Write),
        ssl_negotiate(SSL, Read, Write, SecureRead, SecureWrite).

my_verify(_SSL, _Error, _All, _First, <b>verified</b>).
</pre>

Unfortunately, this does not work (reproducible on OSX and Debian 8.2):

<pre>
?- ssl('fsf.org', 443, _, _).
<b>ERROR: SSL(14090086) ssl3_get_server_certificate: certificate verify failed</b>
</pre>

The reason is that in this certificate chain, we get one `hostname_mismatch`, which does not match `verified`.

However, when I use for example `openssl`, I see that the certificate is at least eventually trusted even when using only system root certificates:

<pre>
$ openssl s_client -connect fsf.org:443
...
Certificate chain
 0 s:/OU=Domain Control Validated/OU=Gandi Standard Wildcard SSL/CN=*.fsf.org
   i:/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
 1 s:/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
   i:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
 2 s:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
...
    Verify return code: 0 (<b>ok</b>)
</pre>

**Comment by JanWielemaker** [comment]
On 01/29/2016 03:49 PM, Markus Triska wrote:
> What is the best way to establish an SSL connection using only the
> *system* root certificates?
>
>  From the documentation, I get the impression that one way to do it is:
>
> :- use_module(library(ssl)).
>
> ssl(Host, Port, SecureRead, SecureWrite) :-
>          ssl_context(client, SSL, [*cacert_file(system(root_certificates)), cert_verify_hook(my_verify)*]),
>          tcp_connect(Host:Port, StreamPair, []),
>          stream_pair(StreamPair, Read, Write),
>          ssl_negotiate(SSL, Read, Write, SecureRead, SecureWrite).
>
> my_verify(_SSL, _Error, _All, _First,*verified*).

Using

my_verify(_SSL, _Error, _All, _First, Verified) :-
	format('My verify: ~q~n', [Verified]).

I get:

My verify: hostname_mismatch
My verify: verified
My verify: verified
My verify: verified
My verify: verified

Not sure how to interpret that.  My (wild) guess would be a hostname 
mismatch in the actual certificate and a valid chain to something 
trusted.  With default options as used by http_open/3, fsf.org is
accepted.

Possibly Matt has some more background.

	Cheers --- Jan

**Comment by FunctionAnalysis** [comment]
Clients do not accept any root if it has not been previously accepted.  To only use a system root for ssl, the server has to provide a chain to the client so the client is able to verify the server, which requires some already trusted intermediary in the chain provided.  Once this is done, the server is trusted. If the client receives the root certificate from a server without the chain, it won't authenticate and the handshake will fail.

It looks like the issue might be somewhere in the chain so that it just needs to renegotiate a few more times for verification.  This means that an intermediate certificate failed verification, so a new intermediate that already has trust between the client and server was used to verify the connection.  If it continues to fail at first, but succeed after a few more iterations it could be a "zero-trust" handshake.  This form of handshake is ephemeral in trust, so every attempt to connect would require re-verification.  If that's the case, the handshake renegotiation should work eventually based on a trusted intermediate like it appears to have done already.

If the issue is an intermediate in the chain, since the negotiation would add the successfully verified steps in place of where it failed, the same test case shouldn't fail again if it isn't a zero-trust system.

If you can get a verbose output of the hostname that is mismatched, you might be able to replace it with a new intermediary that can be verified.

This is an opposite (just as wild) guess as Jan.

**Comment by FunctionAnalysis** [comment]
See #25

**Comment by triska** [comment]
The solution was to use the (previously undocumented) `host/1` option:

<pre>
ssl(Host, Port, SecureRead, SecureWrite) :-
        ssl_context(client, SSL, [cacert_file(system(root_certificates)),
                                  <b>host(Host)</b>,
                                  cert_verify_hook(my_verify)]),
        tcp_connect(Host:Port, StreamPair, []),
        stream_pair(StreamPair, Read, Write),
        ssl_negotiate(SSL, Read, Write, SecureRead, SecureWrite).
</pre>

Fixed with #28. Thank you!
