### ISSUE TITLE
Unexpected end-of-file

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-ssl#73]
The following error is quite regularly written to stderr when I'm running a ClioPatria server with startup command `swipl daemon.pl --http --redirect --https --user=<USER> --certfile=<FILE> --keyfile=<FILE>`.

```
ERROR: [Thread httpsd443_1] SSL(SSL_eof) negotiate: Unexpected end-of-file
```

I'm not sure what this means or what to think of this :-(

I'm using today's checkout of the master branch on Fedora 24.  The certificates are generated by *Let's Encrypt*.

**Comment by triska** [comment]
This indicates that a client began a handshake, and then stopped. Nothing unusual on the&nbsp;web. In fact, one of the most harmless things to&nbsp;happen.

You get many such messages if you use for example utilities like `sslscan` or `nmap` to exhaustively enumerate supported protocols of your server. These tools do not perform a complete handshake, but stop as soon as they have found out enough.

This *is* an issue if "serious" connections get discarded in this way.

If you want to look further into this, consider logging the IP addresses of clients that cause such messages, and capturing more of the traffic. Chances are that such requests predominantly originate from places that are comparatively unlikely to have serious interest in your content, and instead simply scan available servers for weak ciphers.

It's still an error of course, and the thread will drop this connection and be ready for the next&nbsp;one.

Compare this with `/var/log/auth.log`: There will be regular attempts to log in as soon as your server is connected to the web, and most of these attempts are simply discarded.

**Comment by JanWielemaker** [comment]
My guess is a portscan or some  other reason why a client connects but doesn''t complete the SSL handshake.On Dec 9, 2016 22:05, Wouter Beek <notifications@github.com> wrote:The following error is quite regularly written to stderr when I'm running a ClioPatria server with startup command swipl daemon.pl --http --redirect --https --user=<USER> --certfile=<FILE> --keyfile=<FILE>.
ERROR: [Thread httpsd443_1] SSL(SSL_eof) negotiate: Unexpected end-of-file

I'm not sure what this means or what to think of this :-(
I'm using today's checkout of the master branch on Fedora 24.

**Comment by triska** [comment]
@wouterbeek: It seems you are also hitting #25: I have just tried:

<pre>
$ <b>openssl s_client -connect vrijheidzondermaar.nl:443</b>
CONNECTED(00000003)
</pre>

and this hangs, and now works again (presumably because a thread has become available or you have restarted the server).

If you have your server still running, please try:

<pre>
?- <b>threads</b>.
</pre>

This will show how many threads are still alive. The others have crashed.

This "threads are suddenly vanishing" is the most serious issue I am currently trying to track down in the HTTP&nbsp;framework. At this point, I am rather sure that the error is somewhere in the HTTP libraries or kernel, not in the SSL&nbsp;bindings. The issue occurs after days to months of uptime.

If you want to help to track this down, please have a look at the latest [**LetSWICrypt**](https://github.com/triska/letswicrypt) instructions, in particular the section about **Renewing the certificate**, which explains how you can automatically renew the certificate *without* restarting the server. This helps to test the framework over a long time.

Also, if you are interested, try [**SSL&nbsp;LABS**](https://www.ssllabs.com) to test your server. The LetSWICrypt repository explains how to configure stronger ciphers with the SWI&nbsp;infrastructure. If you run the test suite (via ["Test your&nbsp;server"](https://www.ssllabs.com/ssltest/)), you will again see many of the errors you report, because the site makes many connection attempts without completing a full handshake. That's completely&nbsp;OK!

**Comment by JanWielemaker** [comment]
> At this point, I am rather sure that the error is somewhere in the HTTP libraries or kernel, not in the SSL bindings. The issue occurs after days to months of uptime.

We will not know before we find it.  This type of behaviour is not known in plain HTTP servers AFAIK.  Since CDN www.swi-prolog.org's two backend do not get that much traffic anymore (reduced to about 30% by CDN caching and than distributed over two servers).  http://swish.swi-prolog.org is still doing the work alone.  It processes several 100,000s requests per day and doesn't loose threads.  It does suffer from leak issues around Pengines, where somehow pengine resources sometimes survive the pengine death or it doesn't die at all.

**Comment by triska** [comment]
> This type of behaviour is not known in plain HTTP servers AFAIK. 

I am only running a plain HTTP server (in a separate process!) to *redirect* to the HTTPS server, and even in this simple case, this issue once occurred in the plain HTTP server too! There may be a different issue in the SSL bindings too of course, but the plain server is definitely affected as&nbsp;well.

For the SSL bindings, I am making them as safe as I can. Please see the pending pull request #69, which prevents situations that may (in extreme cases) lead to crashes of&nbsp;OpenSSL.

**Comment by JanWielemaker** [comment]
On 12/10/2016 11:14 AM, Markus Triska wrote:
>     This type of behaviour is not known in plain HTTP servers AFAIK.
>
> I am only running a plain HTTP server (in a separate process!) to
> /redirect/ to the HTTPS server, and even in this simple case, this issue
> once occurred in the plain HTTP server too! There may be a different
> issue in the SSL bindings too of course, but the plain server is
> definitely affected as well.

Good to keep in mind ...

> For the SSL bindings, I am making them as safe as I can. Please see the
> pending pull request #69
> <https://github.com/SWI-Prolog/packages-ssl/pull/69>, which prevents
> situations that may (in extreme cases) lead to crashes of OpenSSL.

Sorry, missed that one.  Merged.

	--- Jan

**Comment by wouterbeek** [comment]
@triska This issue can now be closed, right?

**Comment by triska** [comment]
In my view, everything works as expected, and all the issues that were mentioned in addition in this&nbsp;thread are also now corrected.

As a general principle, I leave it to the original reporters to close the issues they have filed once they are fixed from **their** perspective. Everything else typically leads only to half-fixed issues and frustration.
